### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by stan1512** [YvanYin/Metric3D#160]
When I run train.sh using mono/configs/RAFTDecoder/vit.raft5.large.kitti.py I get KeyError: 'dist_params' error，but when I use the mono/configs/RAFTDecoder/vit.raft5.small.kitti.py ,everything is ok ,I'd like to know how I can fix this.

None None
Traceback (most recent call last):
  File "/home/stan1512/anaconda3/envs/metric3d/lib/python3.11/site-packages/mmengine/config/config.py", line 109, in __getattr__
    value = super().__getattr__(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stan1512/anaconda3/envs/metric3d/lib/python3.11/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stan1512/anaconda3/envs/metric3d/lib/python3.11/site-packages/mmengine/config/config.py", line 138, in __getitem__
    return self.build_lazy(super().__getitem__(key))
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stan1512/anaconda3/envs/metric3d/lib/python3.11/site-packages/mmengine/config/config.py", line 105, in __missing__
    raise KeyError(name)
KeyError: 'dist_params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stan1512/training/mono/tools/train.py", line 254, in <module>
    main(args)
  File "/home/stan1512/training/mono/tools/train.py", line 100, in main
    cfg.dist_params.nnodes = args.nnodes
    ^^^^^^^^^^^^^^^
  File "/home/stan1512/anaconda3/envs/metric3d/lib/python3.11/site-packages/mmengine/config/config.py", line 1499, in __getattr__
    return getattr(self._cfg_dict, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stan1512/anaconda3/envs/metric3d/lib/python3.11/site-packages/mmengine/config/config.py", line 113, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'dist_params'

**Comment by JUGGHM** [comment]
It should be some error I have encountered very long ago. Please check whether the **dist_params** are configurated correctly.
