### ISSUE TITLE
torch.hub.load error

### ISSUE THREAD

**Issue by SeungminMun** [YvanYin/Metric3D#89]
Thank you for sharing excellent code and model.
I tried torch.hub.load without cloning this repository, and faced the error below.

Traceback (most recent call last):
  File "/home/XXX.py", line 336, in <module>
    model = torch.hub.load('yvanyin/metric3d', 'metric3d_vit_giant2', pretrain=True).cuda().eval()
  File "/opt/conda/lib/python3.10/site-packages/torch/hub.py", line 568, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/hub.py", line 597, in _load_local
    model = entry(*args, **kwargs)
  File "/home/XXX/.cache/torch/hub/yvanyin_metric3d_main/hubconf.py", line 110, in metric3d_vit_giant2
    cfg = Config.fromfile(cfg_file)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/config/config.py", line 460, in fromfile
    lazy_import is None and not Config._is_lazy_import(filename):
  File "/opt/conda/lib/python3.10/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'mono/configs/HourglassDecoder/vit.raft5.giant2.py'

Could you check?

**Comment by ZachL1** [comment]
It looks like your cache is incomplete, please delete your incomplete cache located at `/home/XXX/.cache/torch/hub/yvanyin_metric3d_main`. Then try `torch.hub.load` again.

Note: Please pay attention to network issues and make sure that `torch.hub.load` has smooth access to github.com to download the code and huggingface.co to download the weights.

**Comment by Gabriellgpc** [comment]
found the issue, I've created a PR for it.
https://github.com/YvanYin/Metric3D/pull/92

i have add small code to convert from relative path to absolute path to get the config file.

**Comment by ZachL1** [comment]
Sorry for my oversight, I just tested and fixed this issue.

@Gabriellgpc Thank you for your kind pr.
